export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const INCREMENT_COUNTER_ASYNC = 'INCREMENT_COUNTER_ASYNC';
export const CANCEL_COUNTER = 'CANCEL_COUNTER';
export const UPDATING_COUNTER = 'UPDATING_COUNTER';
